package cn.zeroce.design.chengwen.wx.mapper;

import cn.zeroce.design.chengwen.wx.entity.PostStorage;
import cn.zeroce.design.chengwen.wx.entity.PostStorageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PostStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_storage
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    long countByExample(PostStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_storage
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    int deleteByExample(PostStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_storage
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    int deleteByPrimaryKey(String pKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_storage
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    int insert(PostStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_storage
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    int insertSelective(PostStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_storage
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    List<PostStorage> selectByExampleWithRowbounds(PostStorageExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_storage
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    List<PostStorage> selectByExample(PostStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_storage
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    PostStorage selectByPrimaryKey(String pKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_storage
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") PostStorage record, @Param("example") PostStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_storage
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    int updateByExample(@Param("record") PostStorage record, @Param("example") PostStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_storage
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    int updateByPrimaryKeySelective(PostStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_storage
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    int updateByPrimaryKey(PostStorage record);
}