package cn.zeroce.design.chengwen.wx.mapper;

import cn.zeroce.design.chengwen.wx.entity.PostPlayforms;
import cn.zeroce.design.chengwen.wx.entity.PostPlayformsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PostPlayformsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_playforms
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    long countByExample(PostPlayformsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_playforms
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    int deleteByExample(PostPlayformsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_playforms
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_playforms
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    int insert(PostPlayforms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_playforms
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    int insertSelective(PostPlayforms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_playforms
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    List<PostPlayforms> selectByExampleWithRowbounds(PostPlayformsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_playforms
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    List<PostPlayforms> selectByExample(PostPlayformsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_playforms
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    PostPlayforms selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_playforms
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    int updateByExampleSelective(@Param("record") PostPlayforms record, @Param("example") PostPlayformsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_playforms
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    int updateByExample(@Param("record") PostPlayforms record, @Param("example") PostPlayformsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_playforms
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    int updateByPrimaryKeySelective(PostPlayforms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_playforms
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    int updateByPrimaryKey(PostPlayforms record);
}