package cn.zeroce.design.chengwen.wx.mapper;

import cn.zeroce.design.chengwen.wx.entity.UserFollow;
import cn.zeroce.design.chengwen.wx.entity.UserFollowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserFollowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    long countByExample(UserFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    int deleteByExample(UserFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    int insert(UserFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    int insertSelective(UserFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    List<UserFollow> selectByExampleWithRowbounds(UserFollowExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    List<UserFollow> selectByExample(UserFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    UserFollow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserFollow record, @Param("example") UserFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    int updateByExample(@Param("record") UserFollow record, @Param("example") UserFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    int updateByPrimaryKeySelective(UserFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    int updateByPrimaryKey(UserFollow record);
}