package cn.zeroce.design.chengwen.wx.mapper;

import cn.zeroce.design.chengwen.wx.entity.UserCollectPost;
import cn.zeroce.design.chengwen.wx.entity.UserCollectPostExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserCollectPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collect_post
     *
     * @mbg.generated Fri May 15 11:44:57 CST 2020
     */
    long countByExample(UserCollectPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collect_post
     *
     * @mbg.generated Fri May 15 11:44:57 CST 2020
     */
    int deleteByExample(UserCollectPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collect_post
     *
     * @mbg.generated Fri May 15 11:44:57 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collect_post
     *
     * @mbg.generated Fri May 15 11:44:57 CST 2020
     */
    int insert(UserCollectPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collect_post
     *
     * @mbg.generated Fri May 15 11:44:57 CST 2020
     */
    int insertSelective(UserCollectPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collect_post
     *
     * @mbg.generated Fri May 15 11:44:57 CST 2020
     */
    List<UserCollectPost> selectByExampleWithRowbounds(UserCollectPostExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collect_post
     *
     * @mbg.generated Fri May 15 11:44:57 CST 2020
     */
    List<UserCollectPost> selectByExample(UserCollectPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collect_post
     *
     * @mbg.generated Fri May 15 11:44:57 CST 2020
     */
    UserCollectPost selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collect_post
     *
     * @mbg.generated Fri May 15 11:44:57 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserCollectPost record, @Param("example") UserCollectPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collect_post
     *
     * @mbg.generated Fri May 15 11:44:57 CST 2020
     */
    int updateByExample(@Param("record") UserCollectPost record, @Param("example") UserCollectPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collect_post
     *
     * @mbg.generated Fri May 15 11:44:57 CST 2020
     */
    int updateByPrimaryKeySelective(UserCollectPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_collect_post
     *
     * @mbg.generated Fri May 15 11:44:57 CST 2020
     */
    int updateByPrimaryKey(UserCollectPost record);
}