package cn.zeroce.design.chengwen.wx.mapper;

import cn.zeroce.design.chengwen.wx.entity.WxUser;
import cn.zeroce.design.chengwen.wx.entity.WxUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WxUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated Mon Apr 20 14:58:56 CST 2020
     */
    long countByExample(WxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated Mon Apr 20 14:58:56 CST 2020
     */
    int deleteByExample(WxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated Mon Apr 20 14:58:56 CST 2020
     */
    int deleteByPrimaryKey(String openid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated Mon Apr 20 14:58:56 CST 2020
     */
    int insert(WxUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated Mon Apr 20 14:58:56 CST 2020
     */
    int insertSelective(WxUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated Mon Apr 20 14:58:56 CST 2020
     */
    List<WxUser> selectByExampleWithRowbounds(WxUserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated Mon Apr 20 14:58:56 CST 2020
     */
    List<WxUser> selectByExample(WxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated Mon Apr 20 14:58:56 CST 2020
     */
    WxUser selectByPrimaryKey(String openid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated Mon Apr 20 14:58:56 CST 2020
     */
    int updateByExampleSelective(@Param("record") WxUser record, @Param("example") WxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated Mon Apr 20 14:58:56 CST 2020
     */
    int updateByExample(@Param("record") WxUser record, @Param("example") WxUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated Mon Apr 20 14:58:56 CST 2020
     */
    int updateByPrimaryKeySelective(WxUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated Mon Apr 20 14:58:56 CST 2020
     */
    int updateByPrimaryKey(WxUser record);
}