package cn.zeroce.design.chengwen.entity;

import java.util.Date;

public class Post {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.id
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.post_title
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    private String postTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.create_time
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.modified_time
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.user_id
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.post_reviewer
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    private String postReviewer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.post_content_short
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    private String postContentShort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.forecast
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    private Float forecast;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.importance
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    private Integer importance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.type
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.status
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.comment_disabled
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    private Boolean commentDisabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.platforms
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    private String platforms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.user_openid
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    private String userOpenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.post_content
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    private String postContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.id
     *
     * @return the value of post.id
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.id
     *
     * @param id the value for post.id
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.post_title
     *
     * @return the value of post.post_title
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public String getPostTitle() {
        return postTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.post_title
     *
     * @param postTitle the value for post.post_title
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public void setPostTitle(String postTitle) {
        this.postTitle = postTitle == null ? null : postTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.create_time
     *
     * @return the value of post.create_time
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.create_time
     *
     * @param createTime the value for post.create_time
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.modified_time
     *
     * @return the value of post.modified_time
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.modified_time
     *
     * @param modifiedTime the value for post.modified_time
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.user_id
     *
     * @return the value of post.user_id
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.user_id
     *
     * @param userId the value for post.user_id
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.post_reviewer
     *
     * @return the value of post.post_reviewer
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public String getPostReviewer() {
        return postReviewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.post_reviewer
     *
     * @param postReviewer the value for post.post_reviewer
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public void setPostReviewer(String postReviewer) {
        this.postReviewer = postReviewer == null ? null : postReviewer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.post_content_short
     *
     * @return the value of post.post_content_short
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public String getPostContentShort() {
        return postContentShort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.post_content_short
     *
     * @param postContentShort the value for post.post_content_short
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public void setPostContentShort(String postContentShort) {
        this.postContentShort = postContentShort == null ? null : postContentShort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.forecast
     *
     * @return the value of post.forecast
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public Float getForecast() {
        return forecast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.forecast
     *
     * @param forecast the value for post.forecast
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public void setForecast(Float forecast) {
        this.forecast = forecast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.importance
     *
     * @return the value of post.importance
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public Integer getImportance() {
        return importance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.importance
     *
     * @param importance the value for post.importance
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public void setImportance(Integer importance) {
        this.importance = importance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.type
     *
     * @return the value of post.type
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.type
     *
     * @param type the value for post.type
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.status
     *
     * @return the value of post.status
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.status
     *
     * @param status the value for post.status
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.comment_disabled
     *
     * @return the value of post.comment_disabled
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public Boolean getCommentDisabled() {
        return commentDisabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.comment_disabled
     *
     * @param commentDisabled the value for post.comment_disabled
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public void setCommentDisabled(Boolean commentDisabled) {
        this.commentDisabled = commentDisabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.platforms
     *
     * @return the value of post.platforms
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public String getPlatforms() {
        return platforms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.platforms
     *
     * @param platforms the value for post.platforms
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public void setPlatforms(String platforms) {
        this.platforms = platforms == null ? null : platforms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.user_openid
     *
     * @return the value of post.user_openid
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public String getUserOpenid() {
        return userOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.user_openid
     *
     * @param userOpenid the value for post.user_openid
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public void setUserOpenid(String userOpenid) {
        this.userOpenid = userOpenid == null ? null : userOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.post_content
     *
     * @return the value of post.post_content
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public String getPostContent() {
        return postContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.post_content
     *
     * @param postContent the value for post.post_content
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    public void setPostContent(String postContent) {
        this.postContent = postContent == null ? null : postContent.trim();
    }
}