package cn.zeroce.design.chengwen.entity;

import java.util.Date;

public class SysAdmin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.id
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.username
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.password
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.token
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.avatar
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.name
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.introduction
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.create_time
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.modified_time
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    private Date modifiedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.id
     *
     * @return the value of sys_admin.id
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.id
     *
     * @param id the value for sys_admin.id
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.username
     *
     * @return the value of sys_admin.username
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.username
     *
     * @param username the value for sys_admin.username
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.password
     *
     * @return the value of sys_admin.password
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.password
     *
     * @param password the value for sys_admin.password
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.token
     *
     * @return the value of sys_admin.token
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.token
     *
     * @param token the value for sys_admin.token
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.avatar
     *
     * @return the value of sys_admin.avatar
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.avatar
     *
     * @param avatar the value for sys_admin.avatar
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.name
     *
     * @return the value of sys_admin.name
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.name
     *
     * @param name the value for sys_admin.name
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.introduction
     *
     * @return the value of sys_admin.introduction
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.introduction
     *
     * @param introduction the value for sys_admin.introduction
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.create_time
     *
     * @return the value of sys_admin.create_time
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.create_time
     *
     * @param createTime the value for sys_admin.create_time
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.modified_time
     *
     * @return the value of sys_admin.modified_time
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.modified_time
     *
     * @param modifiedTime the value for sys_admin.modified_time
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }
}