package cn.zeroce.design.chengwen.entity;

public class SysRoles {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.id
     *
     * @mbg.generated Sat Mar 14 16:12:37 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.name
     *
     * @mbg.generated Sat Mar 14 16:12:37 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.id
     *
     * @return the value of sys_roles.id
     *
     * @mbg.generated Sat Mar 14 16:12:37 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.id
     *
     * @param id the value for sys_roles.id
     *
     * @mbg.generated Sat Mar 14 16:12:37 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.name
     *
     * @return the value of sys_roles.name
     *
     * @mbg.generated Sat Mar 14 16:12:37 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.name
     *
     * @param name the value for sys_roles.name
     *
     * @mbg.generated Sat Mar 14 16:12:37 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}