package cn.zeroce.design.chengwen.entity;

public class SysRolesPermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles_permission.id
     *
     * @mbg.generated Sat Mar 14 16:52:59 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles_permission.sys_roles_id
     *
     * @mbg.generated Sat Mar 14 16:52:59 CST 2020
     */
    private Integer sysRolesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles_permission.sys_permission_id
     *
     * @mbg.generated Sat Mar 14 16:52:59 CST 2020
     */
    private Integer sysPermissionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles_permission.id
     *
     * @return the value of sys_roles_permission.id
     *
     * @mbg.generated Sat Mar 14 16:52:59 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles_permission.id
     *
     * @param id the value for sys_roles_permission.id
     *
     * @mbg.generated Sat Mar 14 16:52:59 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles_permission.sys_roles_id
     *
     * @return the value of sys_roles_permission.sys_roles_id
     *
     * @mbg.generated Sat Mar 14 16:52:59 CST 2020
     */
    public Integer getSysRolesId() {
        return sysRolesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles_permission.sys_roles_id
     *
     * @param sysRolesId the value for sys_roles_permission.sys_roles_id
     *
     * @mbg.generated Sat Mar 14 16:52:59 CST 2020
     */
    public void setSysRolesId(Integer sysRolesId) {
        this.sysRolesId = sysRolesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles_permission.sys_permission_id
     *
     * @return the value of sys_roles_permission.sys_permission_id
     *
     * @mbg.generated Sat Mar 14 16:52:59 CST 2020
     */
    public Integer getSysPermissionId() {
        return sysPermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles_permission.sys_permission_id
     *
     * @param sysPermissionId the value for sys_roles_permission.sys_permission_id
     *
     * @mbg.generated Sat Mar 14 16:52:59 CST 2020
     */
    public void setSysPermissionId(Integer sysPermissionId) {
        this.sysPermissionId = sysPermissionId;
    }
}