package cn.zeroce.design.chengwen.entity;

import java.util.Date;

public class SysStorage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_storage.id
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_storage.s_key
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    private String sKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_storage.s_name
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    private String sName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_storage.type
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_storage.size
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    private Integer size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_storage.url
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_storage.create_time
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_storage.modified_time
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_storage.deleted
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_storage.id
     *
     * @return the value of sys_storage.id
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_storage.id
     *
     * @param id the value for sys_storage.id
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_storage.s_key
     *
     * @return the value of sys_storage.s_key
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    public String getsKey() {
        return sKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_storage.s_key
     *
     * @param sKey the value for sys_storage.s_key
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    public void setsKey(String sKey) {
        this.sKey = sKey == null ? null : sKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_storage.s_name
     *
     * @return the value of sys_storage.s_name
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_storage.s_name
     *
     * @param sName the value for sys_storage.s_name
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_storage.type
     *
     * @return the value of sys_storage.type
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_storage.type
     *
     * @param type the value for sys_storage.type
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_storage.size
     *
     * @return the value of sys_storage.size
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_storage.size
     *
     * @param size the value for sys_storage.size
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_storage.url
     *
     * @return the value of sys_storage.url
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_storage.url
     *
     * @param url the value for sys_storage.url
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_storage.create_time
     *
     * @return the value of sys_storage.create_time
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_storage.create_time
     *
     * @param createTime the value for sys_storage.create_time
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_storage.modified_time
     *
     * @return the value of sys_storage.modified_time
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_storage.modified_time
     *
     * @param modifiedTime the value for sys_storage.modified_time
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_storage.deleted
     *
     * @return the value of sys_storage.deleted
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_storage.deleted
     *
     * @param deleted the value for sys_storage.deleted
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}