package cn.zeroce.design.chengwen.entity;

public class Tag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.id
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.tag_name
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    private String tagName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.tag_refer_count
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    private Integer tagReferCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.id
     *
     * @return the value of tag.id
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.id
     *
     * @param id the value for tag.id
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.tag_name
     *
     * @return the value of tag.tag_name
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.tag_name
     *
     * @param tagName the value for tag.tag_name
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.tag_refer_count
     *
     * @return the value of tag.tag_refer_count
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    public Integer getTagReferCount() {
        return tagReferCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.tag_refer_count
     *
     * @param tagReferCount the value for tag.tag_refer_count
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    public void setTagReferCount(Integer tagReferCount) {
        this.tagReferCount = tagReferCount;
    }
}