package cn.zeroce.design.chengwen.entity;

public class UserFollow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_follow.id
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_follow.follower_id
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    private Integer followerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_follow.followed_id
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    private Integer followedId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_follow.id
     *
     * @return the value of user_follow.id
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_follow.id
     *
     * @param id the value for user_follow.id
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_follow.follower_id
     *
     * @return the value of user_follow.follower_id
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    public Integer getFollowerId() {
        return followerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_follow.follower_id
     *
     * @param followerId the value for user_follow.follower_id
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    public void setFollowerId(Integer followerId) {
        this.followerId = followerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_follow.followed_id
     *
     * @return the value of user_follow.followed_id
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    public Integer getFollowedId() {
        return followedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_follow.followed_id
     *
     * @param followedId the value for user_follow.followed_id
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    public void setFollowedId(Integer followedId) {
        this.followedId = followedId;
    }
}