package cn.zeroce.design.chengwen.mapper;

import cn.zeroce.design.chengwen.entity.PostCatagory;
import cn.zeroce.design.chengwen.entity.PostCatagoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PostCatagoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_catagory
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    long countByExample(PostCatagoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_catagory
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    int deleteByExample(PostCatagoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_catagory
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_catagory
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    int insert(PostCatagory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_catagory
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    int insertSelective(PostCatagory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_catagory
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    List<PostCatagory> selectByExampleWithRowbounds(PostCatagoryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_catagory
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    List<PostCatagory> selectByExample(PostCatagoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_catagory
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    PostCatagory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_catagory
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    int updateByExampleSelective(@Param("record") PostCatagory record, @Param("example") PostCatagoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_catagory
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    int updateByExample(@Param("record") PostCatagory record, @Param("example") PostCatagoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_catagory
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    int updateByPrimaryKeySelective(PostCatagory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_catagory
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    int updateByPrimaryKey(PostCatagory record);
}