package cn.zeroce.design.chengwen.mapper;

import cn.zeroce.design.chengwen.entity.PostDetails;
import cn.zeroce.design.chengwen.entity.PostDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PostDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_details
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    long countByExample(PostDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_details
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    int deleteByExample(PostDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_details
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    int deleteByPrimaryKey(Integer postId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_details
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    int insert(PostDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_details
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    int insertSelective(PostDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_details
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    List<PostDetails> selectByExampleWithRowbounds(PostDetailsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_details
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    List<PostDetails> selectByExample(PostDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_details
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    PostDetails selectByPrimaryKey(Integer postId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_details
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    int updateByExampleSelective(@Param("record") PostDetails record, @Param("example") PostDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_details
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    int updateByExample(@Param("record") PostDetails record, @Param("example") PostDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_details
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    int updateByPrimaryKeySelective(PostDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_details
     *
     * @mbg.generated Thu May 07 18:17:34 CST 2020
     */
    int updateByPrimaryKey(PostDetails record);
}