package cn.zeroce.design.chengwen.mapper;

import cn.zeroce.design.chengwen.dto.SysAdminWithRolePermissionDTO;
import cn.zeroce.design.chengwen.dto.SysAdminWithRolesDTO;
import cn.zeroce.design.chengwen.dto.SysRolesDTO;
import cn.zeroce.design.chengwen.entity.SysAdmin;
import cn.zeroce.design.chengwen.entity.SysAdminExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SysAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    long countByExample(SysAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    int deleteByExample(SysAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    int insert(SysAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    int insertSelective(SysAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    List<SysAdmin> selectByExampleWithRowbounds(SysAdminExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    List<SysAdmin> selectByExample(SysAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    SysAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysAdmin record, @Param("example") SysAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    int updateByExample(@Param("record") SysAdmin record, @Param("example") SysAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    int updateByPrimaryKeySelective(SysAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbg.generated Mon Mar 30 14:54:01 CST 2020
     */
    int updateByPrimaryKey(SysAdmin record);

    List<SysRolesDTO> selectForAllWithRole();

    SysAdminWithRolePermissionDTO findPerDetailBy(Map<String, Object> map);

    List<SysAdminWithRolesDTO> findWithRolesBy(Map<String, Object> params);

    List<SysAdmin> findPublicPros(Map<String, Object> params);

    SysAdminWithRolesDTO findRolesDetailBy(Map<String, Object> params);
}