package cn.zeroce.design.chengwen.mapper;

import cn.zeroce.design.chengwen.entity.SysAdminRoles;
import cn.zeroce.design.chengwen.entity.SysAdminRolesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SysAdminRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_roles
     *
     * @mbg.generated Fri Mar 20 21:11:16 CST 2020
     */
    long countByExample(SysAdminRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_roles
     *
     * @mbg.generated Fri Mar 20 21:11:16 CST 2020
     */
    int deleteByExample(SysAdminRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_roles
     *
     * @mbg.generated Fri Mar 20 21:11:16 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_roles
     *
     * @mbg.generated Fri Mar 20 21:11:16 CST 2020
     */
    int insert(SysAdminRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_roles
     *
     * @mbg.generated Fri Mar 20 21:11:16 CST 2020
     */
    int insertSelective(SysAdminRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_roles
     *
     * @mbg.generated Fri Mar 20 21:11:16 CST 2020
     */
    List<SysAdminRoles> selectByExampleWithRowbounds(SysAdminRolesExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_roles
     *
     * @mbg.generated Fri Mar 20 21:11:16 CST 2020
     */
    List<SysAdminRoles> selectByExample(SysAdminRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_roles
     *
     * @mbg.generated Fri Mar 20 21:11:16 CST 2020
     */
    SysAdminRoles selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_roles
     *
     * @mbg.generated Fri Mar 20 21:11:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysAdminRoles record, @Param("example") SysAdminRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_roles
     *
     * @mbg.generated Fri Mar 20 21:11:16 CST 2020
     */
    int updateByExample(@Param("record") SysAdminRoles record, @Param("example") SysAdminRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_roles
     *
     * @mbg.generated Fri Mar 20 21:11:16 CST 2020
     */
    int updateByPrimaryKeySelective(SysAdminRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_roles
     *
     * @mbg.generated Fri Mar 20 21:11:16 CST 2020
     */
    int updateByPrimaryKey(SysAdminRoles record);
}