package cn.zeroce.design.chengwen.mapper;

import cn.zeroce.design.chengwen.entity.SysRoles;
import cn.zeroce.design.chengwen.entity.SysRolesExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SysRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbg.generated Sat Mar 14 16:12:37 CST 2020
     */
    long countByExample(SysRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbg.generated Sat Mar 14 16:12:37 CST 2020
     */
    int deleteByExample(SysRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbg.generated Sat Mar 14 16:12:37 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbg.generated Sat Mar 14 16:12:37 CST 2020
     */
    int insert(SysRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbg.generated Sat Mar 14 16:12:37 CST 2020
     */
    int insertSelective(SysRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbg.generated Sat Mar 14 16:12:37 CST 2020
     */
    List<SysRoles> selectByExampleWithRowbounds(SysRolesExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbg.generated Sat Mar 14 16:12:37 CST 2020
     */
    List<SysRoles> selectByExample(SysRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbg.generated Sat Mar 14 16:12:37 CST 2020
     */
    SysRoles selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbg.generated Sat Mar 14 16:12:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysRoles record, @Param("example") SysRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbg.generated Sat Mar 14 16:12:37 CST 2020
     */
    int updateByExample(@Param("record") SysRoles record, @Param("example") SysRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbg.generated Sat Mar 14 16:12:37 CST 2020
     */
    int updateByPrimaryKeySelective(SysRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbg.generated Sat Mar 14 16:12:37 CST 2020
     */
    int updateByPrimaryKey(SysRoles record);

    /**
     * 按条件查询所有角色信息
     * @param map
     * @return 角色列表
     */
    List<SysRoles> selectAllBy(Map<String, Object> map);
}