package cn.zeroce.design.chengwen.mapper;

import cn.zeroce.design.chengwen.entity.SysRolesPermission;
import cn.zeroce.design.chengwen.entity.SysRolesPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SysRolesPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permission
     *
     * @mbg.generated Sat Mar 14 16:52:59 CST 2020
     */
    long countByExample(SysRolesPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permission
     *
     * @mbg.generated Sat Mar 14 16:52:59 CST 2020
     */
    int deleteByExample(SysRolesPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permission
     *
     * @mbg.generated Sat Mar 14 16:52:59 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permission
     *
     * @mbg.generated Sat Mar 14 16:52:59 CST 2020
     */
    int insert(SysRolesPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permission
     *
     * @mbg.generated Sat Mar 14 16:52:59 CST 2020
     */
    int insertSelective(SysRolesPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permission
     *
     * @mbg.generated Sat Mar 14 16:52:59 CST 2020
     */
    List<SysRolesPermission> selectByExampleWithRowbounds(SysRolesPermissionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permission
     *
     * @mbg.generated Sat Mar 14 16:52:59 CST 2020
     */
    List<SysRolesPermission> selectByExample(SysRolesPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permission
     *
     * @mbg.generated Sat Mar 14 16:52:59 CST 2020
     */
    SysRolesPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permission
     *
     * @mbg.generated Sat Mar 14 16:52:59 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysRolesPermission record, @Param("example") SysRolesPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permission
     *
     * @mbg.generated Sat Mar 14 16:52:59 CST 2020
     */
    int updateByExample(@Param("record") SysRolesPermission record, @Param("example") SysRolesPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permission
     *
     * @mbg.generated Sat Mar 14 16:52:59 CST 2020
     */
    int updateByPrimaryKeySelective(SysRolesPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles_permission
     *
     * @mbg.generated Sat Mar 14 16:52:59 CST 2020
     */
    int updateByPrimaryKey(SysRolesPermission record);
}