package cn.zeroce.design.chengwen.mapper;

import cn.zeroce.design.chengwen.entity.SysStorage;
import cn.zeroce.design.chengwen.entity.SysStorageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SysStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_storage
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    long countByExample(SysStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_storage
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    int deleteByExample(SysStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_storage
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_storage
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    int insert(SysStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_storage
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    int insertSelective(SysStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_storage
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    List<SysStorage> selectByExampleWithRowbounds(SysStorageExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_storage
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    List<SysStorage> selectByExample(SysStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_storage
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    SysStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_storage
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysStorage record, @Param("example") SysStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_storage
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    int updateByExample(@Param("record") SysStorage record, @Param("example") SysStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_storage
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    int updateByPrimaryKeySelective(SysStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_storage
     *
     * @mbg.generated Sat Apr 11 22:11:04 CST 2020
     */
    int updateByPrimaryKey(SysStorage record);
}