package cn.zeroce.design.chengwen.mapper;

import cn.zeroce.design.chengwen.entity.UserThumbupComment;
import cn.zeroce.design.chengwen.entity.UserThumbupCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserThumbupCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_thumbup_comment
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    long countByExample(UserThumbupCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_thumbup_comment
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    int deleteByExample(UserThumbupCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_thumbup_comment
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_thumbup_comment
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    int insert(UserThumbupComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_thumbup_comment
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    int insertSelective(UserThumbupComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_thumbup_comment
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    List<UserThumbupComment> selectByExampleWithRowbounds(UserThumbupCommentExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_thumbup_comment
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    List<UserThumbupComment> selectByExample(UserThumbupCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_thumbup_comment
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    UserThumbupComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_thumbup_comment
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserThumbupComment record, @Param("example") UserThumbupCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_thumbup_comment
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    int updateByExample(@Param("record") UserThumbupComment record, @Param("example") UserThumbupCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_thumbup_comment
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    int updateByPrimaryKeySelective(UserThumbupComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_thumbup_comment
     *
     * @mbg.generated Fri Mar 13 17:47:14 CST 2020
     */
    int updateByPrimaryKey(UserThumbupComment record);
}