package cn.zeroce.design.chengwen.wx.entity;

public class PostDetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_details.post_id
     *
     * @mbg.generated Fri May 15 11:34:03 CST 2020
     */
    private Integer postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_details.collected_count
     *
     * @mbg.generated Fri May 15 11:34:03 CST 2020
     */
    private Integer collectedCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_details.thumb_up_count
     *
     * @mbg.generated Fri May 15 11:34:03 CST 2020
     */
    private Integer thumbUpCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_details.thumb_down_count
     *
     * @mbg.generated Fri May 15 11:34:03 CST 2020
     */
    private Integer thumbDownCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_details.view_count
     *
     * @mbg.generated Fri May 15 11:34:03 CST 2020
     */
    private Integer viewCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_details.post_id
     *
     * @return the value of post_details.post_id
     *
     * @mbg.generated Fri May 15 11:34:03 CST 2020
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_details.post_id
     *
     * @param postId the value for post_details.post_id
     *
     * @mbg.generated Fri May 15 11:34:03 CST 2020
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_details.collected_count
     *
     * @return the value of post_details.collected_count
     *
     * @mbg.generated Fri May 15 11:34:03 CST 2020
     */
    public Integer getCollectedCount() {
        return collectedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_details.collected_count
     *
     * @param collectedCount the value for post_details.collected_count
     *
     * @mbg.generated Fri May 15 11:34:03 CST 2020
     */
    public void setCollectedCount(Integer collectedCount) {
        this.collectedCount = collectedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_details.thumb_up_count
     *
     * @return the value of post_details.thumb_up_count
     *
     * @mbg.generated Fri May 15 11:34:03 CST 2020
     */
    public Integer getThumbUpCount() {
        return thumbUpCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_details.thumb_up_count
     *
     * @param thumbUpCount the value for post_details.thumb_up_count
     *
     * @mbg.generated Fri May 15 11:34:03 CST 2020
     */
    public void setThumbUpCount(Integer thumbUpCount) {
        this.thumbUpCount = thumbUpCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_details.thumb_down_count
     *
     * @return the value of post_details.thumb_down_count
     *
     * @mbg.generated Fri May 15 11:34:03 CST 2020
     */
    public Integer getThumbDownCount() {
        return thumbDownCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_details.thumb_down_count
     *
     * @param thumbDownCount the value for post_details.thumb_down_count
     *
     * @mbg.generated Fri May 15 11:34:03 CST 2020
     */
    public void setThumbDownCount(Integer thumbDownCount) {
        this.thumbDownCount = thumbDownCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_details.view_count
     *
     * @return the value of post_details.view_count
     *
     * @mbg.generated Fri May 15 11:34:03 CST 2020
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_details.view_count
     *
     * @param viewCount the value for post_details.view_count
     *
     * @mbg.generated Fri May 15 11:34:03 CST 2020
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }
}