package cn.zeroce.design.chengwen.wx.entity;

import java.util.Date;

public class PostStorage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_storage.p_key
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    private String pKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_storage.p_name
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    private String pName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_storage.type
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_storage.size
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    private Integer size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_storage.url
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_storage.create_time
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_storage.modified_time
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_storage.deleted
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_storage.p_key
     *
     * @return the value of post_storage.p_key
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    public String getpKey() {
        return pKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_storage.p_key
     *
     * @param pKey the value for post_storage.p_key
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    public void setpKey(String pKey) {
        this.pKey = pKey == null ? null : pKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_storage.p_name
     *
     * @return the value of post_storage.p_name
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_storage.p_name
     *
     * @param pName the value for post_storage.p_name
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_storage.type
     *
     * @return the value of post_storage.type
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_storage.type
     *
     * @param type the value for post_storage.type
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_storage.size
     *
     * @return the value of post_storage.size
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_storage.size
     *
     * @param size the value for post_storage.size
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_storage.url
     *
     * @return the value of post_storage.url
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_storage.url
     *
     * @param url the value for post_storage.url
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_storage.create_time
     *
     * @return the value of post_storage.create_time
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_storage.create_time
     *
     * @param createTime the value for post_storage.create_time
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_storage.modified_time
     *
     * @return the value of post_storage.modified_time
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_storage.modified_time
     *
     * @param modifiedTime the value for post_storage.modified_time
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_storage.deleted
     *
     * @return the value of post_storage.deleted
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_storage.deleted
     *
     * @param deleted the value for post_storage.deleted
     *
     * @mbg.generated Wed Apr 22 23:01:16 CST 2020
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}