package cn.zeroce.design.chengwen.wx.entity;

import java.util.Date;

public class PostImageUrls {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_image_urls.id
     *
     * @mbg.generated Fri Apr 24 11:09:11 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_image_urls.post_id
     *
     * @mbg.generated Fri Apr 24 11:09:11 CST 2020
     */
    private Integer postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_image_urls.image_url
     *
     * @mbg.generated Fri Apr 24 11:09:11 CST 2020
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_image_urls.create_time
     *
     * @mbg.generated Fri Apr 24 11:09:11 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_image_urls.id
     *
     * @return the value of post_image_urls.id
     *
     * @mbg.generated Fri Apr 24 11:09:11 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_image_urls.id
     *
     * @param id the value for post_image_urls.id
     *
     * @mbg.generated Fri Apr 24 11:09:11 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_image_urls.post_id
     *
     * @return the value of post_image_urls.post_id
     *
     * @mbg.generated Fri Apr 24 11:09:11 CST 2020
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_image_urls.post_id
     *
     * @param postId the value for post_image_urls.post_id
     *
     * @mbg.generated Fri Apr 24 11:09:11 CST 2020
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_image_urls.image_url
     *
     * @return the value of post_image_urls.image_url
     *
     * @mbg.generated Fri Apr 24 11:09:11 CST 2020
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_image_urls.image_url
     *
     * @param imageUrl the value for post_image_urls.image_url
     *
     * @mbg.generated Fri Apr 24 11:09:11 CST 2020
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_image_urls.create_time
     *
     * @return the value of post_image_urls.create_time
     *
     * @mbg.generated Fri Apr 24 11:09:11 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_image_urls.create_time
     *
     * @param createTime the value for post_image_urls.create_time
     *
     * @mbg.generated Fri Apr 24 11:09:11 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}