package cn.zeroce.design.chengwen.wx.entity;

import java.util.Date;

public class UserCollectPost {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_collect_post.id
     *
     * @mbg.generated Fri May 15 11:44:57 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_collect_post.collector_id
     *
     * @mbg.generated Fri May 15 11:44:57 CST 2020
     */
    private Integer collectorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_collect_post.collected_post_id
     *
     * @mbg.generated Fri May 15 11:44:57 CST 2020
     */
    private Integer collectedPostId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_collect_post.modified_time
     *
     * @mbg.generated Fri May 15 11:44:57 CST 2020
     */
    private Date modifiedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_collect_post.id
     *
     * @return the value of user_collect_post.id
     *
     * @mbg.generated Fri May 15 11:44:57 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_collect_post.id
     *
     * @param id the value for user_collect_post.id
     *
     * @mbg.generated Fri May 15 11:44:57 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_collect_post.collector_id
     *
     * @return the value of user_collect_post.collector_id
     *
     * @mbg.generated Fri May 15 11:44:57 CST 2020
     */
    public Integer getCollectorId() {
        return collectorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_collect_post.collector_id
     *
     * @param collectorId the value for user_collect_post.collector_id
     *
     * @mbg.generated Fri May 15 11:44:57 CST 2020
     */
    public void setCollectorId(Integer collectorId) {
        this.collectorId = collectorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_collect_post.collected_post_id
     *
     * @return the value of user_collect_post.collected_post_id
     *
     * @mbg.generated Fri May 15 11:44:57 CST 2020
     */
    public Integer getCollectedPostId() {
        return collectedPostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_collect_post.collected_post_id
     *
     * @param collectedPostId the value for user_collect_post.collected_post_id
     *
     * @mbg.generated Fri May 15 11:44:57 CST 2020
     */
    public void setCollectedPostId(Integer collectedPostId) {
        this.collectedPostId = collectedPostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_collect_post.modified_time
     *
     * @return the value of user_collect_post.modified_time
     *
     * @mbg.generated Fri May 15 11:44:57 CST 2020
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_collect_post.modified_time
     *
     * @param modifiedTime the value for user_collect_post.modified_time
     *
     * @mbg.generated Fri May 15 11:44:57 CST 2020
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }
}