package cn.zeroce.design.chengwen.wx.entity;

import java.util.Date;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_nickname
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    private String userNickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_avatarurl
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    private String userAvatarurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_gender
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    private Byte userGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_openid
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    private String userOpenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.language
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    private String language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.create_time
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.modified_time
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_mobile_type
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    private String userMobileType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_telnum
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    private String userTelnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.isAdmin
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    private Boolean isadmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.session_id
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    private String sessionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.session_key
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    private String sessionKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_nickname
     *
     * @return the value of users.user_nickname
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    public String getUserNickname() {
        return userNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_nickname
     *
     * @param userNickname the value for users.user_nickname
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    public void setUserNickname(String userNickname) {
        this.userNickname = userNickname == null ? null : userNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_avatarurl
     *
     * @return the value of users.user_avatarurl
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    public String getUserAvatarurl() {
        return userAvatarurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_avatarurl
     *
     * @param userAvatarurl the value for users.user_avatarurl
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    public void setUserAvatarurl(String userAvatarurl) {
        this.userAvatarurl = userAvatarurl == null ? null : userAvatarurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_gender
     *
     * @return the value of users.user_gender
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    public Byte getUserGender() {
        return userGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_gender
     *
     * @param userGender the value for users.user_gender
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    public void setUserGender(Byte userGender) {
        this.userGender = userGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_openid
     *
     * @return the value of users.user_openid
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    public String getUserOpenid() {
        return userOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_openid
     *
     * @param userOpenid the value for users.user_openid
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    public void setUserOpenid(String userOpenid) {
        this.userOpenid = userOpenid == null ? null : userOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.language
     *
     * @return the value of users.language
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.language
     *
     * @param language the value for users.language
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.create_time
     *
     * @return the value of users.create_time
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.create_time
     *
     * @param createTime the value for users.create_time
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.modified_time
     *
     * @return the value of users.modified_time
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.modified_time
     *
     * @param modifiedTime the value for users.modified_time
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_mobile_type
     *
     * @return the value of users.user_mobile_type
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    public String getUserMobileType() {
        return userMobileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_mobile_type
     *
     * @param userMobileType the value for users.user_mobile_type
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    public void setUserMobileType(String userMobileType) {
        this.userMobileType = userMobileType == null ? null : userMobileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_telnum
     *
     * @return the value of users.user_telnum
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    public String getUserTelnum() {
        return userTelnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_telnum
     *
     * @param userTelnum the value for users.user_telnum
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    public void setUserTelnum(String userTelnum) {
        this.userTelnum = userTelnum == null ? null : userTelnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.isAdmin
     *
     * @return the value of users.isAdmin
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    public Boolean getIsadmin() {
        return isadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.isAdmin
     *
     * @param isadmin the value for users.isAdmin
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    public void setIsadmin(Boolean isadmin) {
        this.isadmin = isadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.session_id
     *
     * @return the value of users.session_id
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.session_id
     *
     * @param sessionId the value for users.session_id
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId == null ? null : sessionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.session_key
     *
     * @return the value of users.session_key
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    public String getSessionKey() {
        return sessionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.session_key
     *
     * @param sessionKey the value for users.session_key
     *
     * @mbg.generated Sun Apr 19 22:43:38 CST 2020
     */
    public void setSessionKey(String sessionKey) {
        this.sessionKey = sessionKey == null ? null : sessionKey.trim();
    }
}