package cn.zeroce.design.chengwen.wx.entity;

public class UserThumbupComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_thumbup_comment.id
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_thumbup_comment.user_id
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_thumbup_comment.comment_id
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    private Integer commentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_thumbup_comment.id
     *
     * @return the value of user_thumbup_comment.id
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_thumbup_comment.id
     *
     * @param id the value for user_thumbup_comment.id
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_thumbup_comment.user_id
     *
     * @return the value of user_thumbup_comment.user_id
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_thumbup_comment.user_id
     *
     * @param userId the value for user_thumbup_comment.user_id
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_thumbup_comment.comment_id
     *
     * @return the value of user_thumbup_comment.comment_id
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_thumbup_comment.comment_id
     *
     * @param commentId the value for user_thumbup_comment.comment_id
     *
     * @mbg.generated Fri Apr 17 18:10:52 CST 2020
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }
}