package cn.zeroce.design.chengwen.wx.entity;

public class WxUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.openid
     *
     * @mbg.generated Mon Apr 20 14:58:56 CST 2020
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.nickname
     *
     * @mbg.generated Mon Apr 20 14:58:56 CST 2020
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.password
     *
     * @mbg.generated Mon Apr 20 14:58:56 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.session_key
     *
     * @mbg.generated Mon Apr 20 14:58:56 CST 2020
     */
    private String sessionKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.openid
     *
     * @return the value of wx_user.openid
     *
     * @mbg.generated Mon Apr 20 14:58:56 CST 2020
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.openid
     *
     * @param openid the value for wx_user.openid
     *
     * @mbg.generated Mon Apr 20 14:58:56 CST 2020
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.nickname
     *
     * @return the value of wx_user.nickname
     *
     * @mbg.generated Mon Apr 20 14:58:56 CST 2020
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.nickname
     *
     * @param nickname the value for wx_user.nickname
     *
     * @mbg.generated Mon Apr 20 14:58:56 CST 2020
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.password
     *
     * @return the value of wx_user.password
     *
     * @mbg.generated Mon Apr 20 14:58:56 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.password
     *
     * @param password the value for wx_user.password
     *
     * @mbg.generated Mon Apr 20 14:58:56 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.session_key
     *
     * @return the value of wx_user.session_key
     *
     * @mbg.generated Mon Apr 20 14:58:56 CST 2020
     */
    public String getSessionKey() {
        return sessionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.session_key
     *
     * @param sessionKey the value for wx_user.session_key
     *
     * @mbg.generated Mon Apr 20 14:58:56 CST 2020
     */
    public void setSessionKey(String sessionKey) {
        this.sessionKey = sessionKey == null ? null : sessionKey.trim();
    }
}